// Generated by CoffeeScript 1.9.3
(function() {
  var additive, isDescending, isDoubleEnded, multiplicative, range;

  module.exports = range = function(a, z, options) {
    var ref;
    if (options == null) {
      options = {
        step: 1
      };
    }
    if (a === void 0) {
      return [];
    }
    if (z === void 0) {
      ref = [a, a < 0 ? -1 : 1], z = ref[0], a = ref[1];
    }
    if (isDescending(a, z, options)) {
      return range(z, a, options).reverse();
    }
    if (options.scale) {
      options.scale = Math.abs(options.scale);
      if (options.scale < 1) {
        options.scale = 1 / options.scale;
      } else if (options.scale === 1) {
        return [];
      }
    } else {
      if (options.step === 0) {
        return [];
      }
      options.step = Math.abs(options.step);
    }
    if (isDoubleEnded(a, z, options)) {
      return range(a, -1, options).concat(range(1, z, options));
    }
    if (options.scale) {
      return multiplicative(a, z, options.scale);
    } else {
      return additive(a, z, options.step);
    }
  };

  isDescending = function(a, z, options) {
    if (!options.scale) {
      return a > z;
    } else {
      return a < 0 && z < 0 && Math.abs(a) > Math.abs(z) || a > 0 && z < 0 || a > 0 && z > 0 && a > z;
    }
  };

  isDoubleEnded = function(a, z, options) {
    return options.scale && a < 0 && z > 0;
  };

  additive = function(lower, upper, step) {
    var array;
    array = [];
    while (Math.round(lower) <= upper) {
      array.push(Math.round(lower));
      lower += step;
    }
    return array;
  };

  multiplicative = function(lower, upper, scale) {
    var array;
    array = [];
    while (Math.round(Math.abs(lower)) <= Math.abs(upper)) {
      array.push(Math.round(lower));
      lower *= scale;
    }
    return array;
  };

}).call(this);
