// Generated by CoffeeScript 1.9.3
var range;

module.exports = range = function(a, z, opts) {
  var array, minus, plus, ref, ref1;
  if (opts == null) {
    opts = {
      step: 1
    };
  }
  if (!a) {
    return [];
  }
  if (!z) {
    ref = [a, a < 0 ? -1 : 1], z = ref[0], a = ref[1];
  }
  array = [];
  if (!opts.scale) {
    if (a > z) {
      return range(z, a, opts).reverse();
    }
    while (Math.round(a) <= z) {
      array.push(Math.round(a));
      a += opts.step;
    }
  } else {
    if (a < 0 && z < 0 && Math.abs(a) > Math.abs(z) || a > 0 && z < 0 || a > 0 && z > 0 && a > z) {
      return range(z, a, opts).reverse();
    } else if (a < 0 && z > 0) {
      ref1 = [range(a, -1, opts), range(1, z, opts)], minus = ref1[0], plus = ref1[1];
      return minus.concat(plus);
    }
    while (Math.round(Math.abs(a)) <= Math.abs(z)) {
      array.push(Math.round(a));
      a *= opts.scale;
    }
  }
  return array;
};
